/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.mycompany.form;

import com.mycompany.event.Model_Data;
import com.mycompany.event.publicEvent;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author User
 */
public class Page_Register extends javax.swing.JPanel {

    /** Creates new form Page_Login */
    public Page_Register() {
        initComponents();
        Color fg = uNField.getForeground();
        
        uNField.addMouseListener(new MouseAdapter(){

            @Override
            public void mouseClicked(MouseEvent e) {
                uNField.setText("");
                uNField.setForeground(Color.BLACK);
                
            }
    
        });
        
        passField.addMouseListener(new MouseAdapter(){

            @Override
            public void mouseClicked(MouseEvent e) {
                passField.setText("");
                passField.setForeground(Color.BLACK);
                
            
            }
      
        });
        
        confPass.addMouseListener(new MouseAdapter(){

            @Override
            public void mouseClicked(MouseEvent e) {
                confPass.setText("");
                confPass.setForeground(Color.BLACK);
            }
           

        });
        
        backLogin.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e) {
                publicEvent.getInstance().getELog().goLogin();
            }
           
       });
    }
    
    public String switchToRegister(){
            return "card3";
        }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        uNField = new javax.swing.JTextField();
        passField = new javax.swing.JTextField();
        confPass = new javax.swing.JTextField();
        registButton = new javax.swing.JButton();
        backLogin = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));

        loginLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        loginLabel.setText("Register");

        uNField.setForeground(new java.awt.Color(224, 224, 224));
        uNField.setText("Username...");

        passField.setForeground(new java.awt.Color(224, 224, 224));
        passField.setText("Password...");
        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });

        confPass.setForeground(new java.awt.Color(224, 224, 224));
        confPass.setText("Confirm Password...");
        confPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confPassActionPerformed(evt);
            }
        });

        registButton.setText("Register");
        registButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registButtonActionPerformed(evt);
            }
        });

        backLogin.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        backLogin.setForeground(new java.awt.Color(253, 155, 114));
        backLogin.setText("Back To Login");
        backLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uNField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(registButton, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(confPass, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(loginLabel))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(backLogin)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(loginLabel)
                .addGap(61, 61, 61)
                .addComponent(uNField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(confPass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(registButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backLogin)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registButtonActionPerformed
        String user = uNField.getText();
        String pass = String.valueOf(passField.getText());
        String confirmPass = String.valueOf(confPass.getText());
        
        if(user.equals("")){
            uNField.grabFocus();
        } else if(pass.equals("")){
            passField.grabFocus();
        } else if(!pass.equals(confirmPass)){
            confPass.grabFocus();
        } else {
            
            System.out.println("input program"+pass);
            Model_Data data = new Model_Data(user, pass);
            System.out.println("output data"+data.getPass());
            System.out.println("output json"+data.toJSONObject());
            
            publicEvent.getInstance().getELog().register(data);
            
        }
        
    }//GEN-LAST:event_registButtonActionPerformed

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    private void backLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backLoginMouseClicked

    private void confPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confPassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLogin;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField confPass;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField passField;
    private javax.swing.JButton registButton;
    private javax.swing.JTextField uNField;
    // End of variables declaration//GEN-END:variables

}
